language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_install:
  # BEGIN: coreir installation
  - mkdir deps
  - cd deps
  - git clone -b dev https://github.com/rdaly525/coreir.git
  - cd coreir
  - export COREIRCONFIG="g++-4.9"
  - export COREIR=$PWD
  - make install -j 2
  - cd ..  # out of coreir
  - cd ..  # out of deps
  # END: coreir installation

script:
  - pip install -e .
  - pytest -s tests/

compiler:
  - gcc

os:
  - linux
